spring:
  application:
    name: BuddyBridge

  datasource:
    url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DATABASE}
    username: ${MARIA_USER}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    open-in-view: false

  session:
    store-type: redis
    redis:
      namespace: test:session

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true

oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    url:
      auth-url: ${OAUTH_KAKAO_AUTH_URL}
      api-url: ${OAUTH_KAKAO_API_URL}
      redirect-url: ${OAUTH_KAKAO_REDIRECT_URI}
      logout-redirect-url:  ${OAUTH_KAKAO_LOGOUT_REDIRECT_URI}
      front-url: ${OAUTH_KAKAO_FRONT_URL}


logging:
  level:
    org.springframework:
      transaction.interceptor: trace    # 트랜잭션 로그 설정

    p6spy: info

    study.learnsocket.auth.kakao: debug # FeignClient 로그 레벨 설정

  file: # 로그 파일 설정
    name: /app/application.log

# Register P6LogFactory to log JDBC events
decorator:
  datasource:
    p6spy:
      enable-logging: true
